const Match = require('../models/Match');
const { calculateVoteTimes } = require('./matchVote.service');

const getNextThursdayAt1930 = (fromDate = new Date()) => {
  const nextThursday = new Date(fromDate);
  const currentDay = nextThursday.getDay();
  const daysUntilNextThursday = ((4 - currentDay + 7) % 7) || 7;

  nextThursday.setDate(nextThursday.getDate() + daysUntilNextThursday);
  nextThursday.setHours(19, 30, 0, 0);

  return nextThursday;
};

const getDateRange = (date) => {
  const start = new Date(date);
  start.setHours(0, 0, 0, 0);

  const end = new Date(date);
  end.setHours(23, 59, 59, 999);

  return { start, end };
};

const createWeeklyThursdayMatch = async () => {
  const matchDate = getNextThursdayAt1930();
  const { start, end } = getDateRange(matchDate);

  const existingMatch = await Match.findOne({
    matchDate: {
      $gte: start,
      $lte: end,
    },
  });

  if (existingMatch) {
    return {
      created: false,
      match: existingMatch,
    };
  }

  const { voteOpenAt, voteCloseAt } = calculateVoteTimes(matchDate);
  const match = await Match.create({
    title: 'Trận đấu hàng tuần',
    matchDate,
    type: 'internal',
    matchStatus: 'next',
    resultStatus: 'not_played',
    homeTeamName: Match.DEFAULT_TEAM_NAME,
    homeTeamLogo: Match.DEFAULT_TEAM_LOGO,
    awayTeamLogo: Match.DEFAULT_TEAM_LOGO,
    voteOpenAt,
    voteCloseAt,
    voteStatus: new Date() < voteOpenAt ? 'not_open' : new Date() < voteCloseAt ? 'open' : 'closed',
    homeScore: 0,
    awayScore: 0,
    bestPlayers: [],
    isAutoGenerated: true,
    isActive: true,
  });

  return {
    created: true,
    match,
  };
};

module.exports = {
  createWeeklyThursdayMatch,
};
