const mongoose = require('mongoose');

const DEFAULT_TEAM_NAME = 'FC Á Châu';
const DEFAULT_TEAM_LOGO = 'https://res.cloudinary.com/demo/image/upload/sample.jpg';

const highlightSchema = new mongoose.Schema(
  {
    minute: {
      type: Number,
    },
    content: {
      type: String,
    },
  },
  {
    _id: false,
  }
);

const matchSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: true,
    },
    opponent: {
      type: String,
      default: '',
    },
    matchDate: {
      type: Date,
      required: true,
    },
    location: {
      type: String,
      default: '',
    },
    type: {
      type: String,
      enum: ['friendly', 'league', 'cup', 'internal', 'other'],
      default: 'internal',
    },
    matchStatus: {
      type: String,
      enum: ['next', 'past'],
      default: 'next',
    },
    resultStatus: {
      type: String,
      enum: ['not_played', 'played'],
      default: 'not_played',
    },
    homeTeamName: {
      type: String,
      default: DEFAULT_TEAM_NAME,
    },
    homeTeamLogo: {
      type: String,
      default: DEFAULT_TEAM_LOGO,
    },
    awayTeamName: {
      type: String,
      default: DEFAULT_TEAM_NAME,
    },
    awayTeamLogo: {
      type: String,
      default: DEFAULT_TEAM_LOGO,
    },
    homeScore: {
      type: Number,
      default: 0,
    },
    awayScore: {
      type: Number,
      default: 0,
    },
    bestPlayers: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Member',
      },
    ],
    voteOpenAt: {
      type: Date,
    },
    voteCloseAt: {
      type: Date,
    },
    voteStatus: {
      type: String,
      enum: ['not_open', 'open', 'closed'],
      default: 'not_open',
    },
    resultNote: {
      type: String,
      default: '',
    },
    description: {
      type: String,
      default: '',
    },
    highlights: [highlightSchema],
    images: [String],
    videoUrl: {
      type: String,
      default: '',
    },
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
    isActive: {
      type: Boolean,
      default: true,
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
  },
  {
    timestamps: true,
  }
);

matchSchema.pre('validate', function (next) {
  if (!this.homeTeamLogo) {
    this.homeTeamLogo = DEFAULT_TEAM_LOGO;
  }

  if (!this.awayTeamLogo) {
    this.awayTeamLogo = DEFAULT_TEAM_LOGO;
  }

  if (this.matchDate) {
    const matchTime = new Date(this.matchDate).getTime();
    this.voteOpenAt = new Date(matchTime + 90 * 60 * 1000);
    this.voteCloseAt = new Date(matchTime + 50 * 60 * 60 * 1000);

    const now = new Date();

    if (now < this.voteOpenAt) {
      this.voteStatus = 'not_open';
    } else if (now < this.voteCloseAt) {
      this.voteStatus = 'open';
    } else {
      this.voteStatus = 'closed';
    }
  }

  next();
});

module.exports = mongoose.model('Match', matchSchema);
module.exports.DEFAULT_TEAM_NAME = DEFAULT_TEAM_NAME;
module.exports.DEFAULT_TEAM_LOGO = DEFAULT_TEAM_LOGO;
